[["展示柜"]]
"名称" = "杂货柜"
"可放类别" = ["书籍绘画", "医疗用品", "家居日用", "数码电子", "文玩古董", "时尚潮流", "武器装备", "特殊藏品", "矿物珠宝", "能源交通", "饮食烹饪"]
"藏品" = []

[["展示柜"]]
"名称" = "家居日用柜"
"可放类别" = ["家居日用"]
"藏品" = []

[["展示柜"]]
"名称" = "医疗用品柜"
"可放类别" = ["医疗用品"]
"藏品" = []

[["展示柜"]]
"名称" = "时尚潮流柜"
"可放类别" = ["时尚潮流"]
"藏品" = []

[["展示柜"]]
"名称" = "武器装备柜"
"可放类别" = ["武器装备"]
"藏品" = []

[["展示柜"]]
"名称" = "矿物珠宝柜"
"可放类别" = ["矿物珠宝"]
"藏品" = []

[["展示柜"]]
"名称" = "文玩古董柜"
"可放类别" = ["文玩古董"]
"藏品" = []

[["展示柜"]]
"名称" = "数码电子柜"
"可放类别" = ["数码电子"]
"藏品" = []

[["展示柜"]]
"名称" = "能源交通柜"
"可放类别" = ["能源交通"]
"藏品" = []

[["展示柜"]]
"名称" = "饮食烹饪柜"
"可放类别" = ["饮食烹饪"]
"藏品" = []

[["展示柜"]]
"名称" = "书籍绘画柜"
"可放类别" = ["书籍绘画"]
"藏品" = []
